[package]
name = "hash_metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.12"
pbkdf2 = "0.11"
rand_core = { version = "0.6", features = ["std"] }

